# action.yml
name: 'Core registry action'
description: 'Interact with the Blockware registry'
inputs:
  action: 
    description: 'Registry action, like pull or push'
    required: true

  credentials: 
    description: 'Blockware credentials, typically a JWT token'
    required: true

  npmrc:
    description: 'NPM registry configuration'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    NPMRC: ${{ inputs.npmrc }}
    BLOCKWARE_CREDENTIALS_TOKEN: ${{ inputs.credentials }} 
  args:
    - ${{ inputs.action }}
    
