# action.yml
name: 'Kapeta Registry'
description: 'Interact with the Kapeta registry'
branding:
  icon: arrow-up-circle
  color: gray-dark
inputs:
  action:
    description: 'Registry action, like publish or validate'
    required: true

  credentials:
    description: 'Kapeta credentials, typically a JWT token'
    required: true

  staging:
    description: 'Kapeta staging, true or false'
    required: false

  base_url:
    description: 'Kapeta base_url, typically used in combination with "staging"'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
