# action.yml
name: 'Core registry action'
description: 'Interact with the Kapeta registry'
inputs:
  action: 
    description: 'Registry action, like publish or validate'
    required: true

  credentials: 
    description: 'Kapeta credentials, typically a JWT token'
    required: true

  npmrc:
    description: 'NPM registry configuration'

runs:
  using: 'node16'
  main: 'dist/index.js'