# action.yml
name: 'Kapeta Registry'
description: 'Interact with the Kapeta registry'
inputs:
  action:
    description: 'Registry action, like publish or validate'
    required: true

  credentials:
    description: 'Kapeta credentials, typically a JWT token'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'